def encrypt_ige(plaintext: bytes, key: bytes, iv: bytes, /) -> bytes: ...
def decrypt_ige(ciphertext: bytes, key: bytes, iv: bytes, /) -> bytes: ...
def factorize_pq_pair(pq: int, /) -> tuple[int, int]: ...
